## TAREA 3

### 1. Definir y predecir

### a) 
* sum(x) nos devuelve el valor de la suma del todos los elementos del vector x,ya que x = {5,2,1,4} el valor esperado sera 12.
* range(x) nos devuelve dos valores, el minimo y maximo valor de los elementos del vetor x,notamosque el minimo valor de x es 1 y el maximo es 5,por lo tanto son los valores esperados.
* length(y) nos devuelve la cantidad de elementos del vector y, ya que y = {1,1,1,1,1} el numero devuelto esperado es 5.

In [1]:
x <- c(5, 2, 1, 4)
y <- rep(1, 5)

sum(x)
range(x)
sum(y)
length(y)
sum(y)


[1] 12

[1] 1 5

[1] 5

[1] 5

[1] 5

### b)
* c(x, y, 13) nos indexa tres vectores: El vector x = {5,2,1,4},y = {1,1,1,1,1} y finalmente el vector {13} , el resultado esperado sera el vector {5,2,1,4,1,1,1,1,1,13}

In [2]:
x <- c(5, 2, 1, 4)
y <- rep(1, 5)
c(x, y, 13)

[1]  5  2  1  4  1  1  1  1  1 13

### c)

* x[4] * y[2] multiplica el 4to valor de x con el 2do valor de y,el valor esperado es 4.
* x[2:4] + x[1:3] nos devuelve un vector de tres elementos, los cuales son el resultado de la suma de x[2]+x[1],x[3]+x[2],x[4]+x[3], ya que x = {5,2,1,4},el vector esperado como resultado es {7,3,5}

In [12]:
x <- c(5, 2, 1, 4)
y <- rep(1, 5)
x[4] * y[2]
x[2:4] + x[1:3]

[1] 4

[1] 7 3 5

### d)

* x <= 2 Nos arroja los elementos de x que son menores o iguales que 2. Resultado esperado: {1,2}
* x[x <= 2] Nos arroja los elementos de las 2 primeras posiciones.Resultado esperado: {5,2}
* x[(x != 5) & (x > 3)] Nos arroja el elemento en la 4ta posicion.Resultado esperado: {4}

In [24]:
x <- c(5, 2, 1, 4)
x <= 2
x[x <= 2]
x[(x != 5) & (x > 3)]

[1] FALSE  TRUE  TRUE FALSE

[1] 2 1

[1] 4

Mi prediccion fue errada,lo correcto es:
* x <= 2 evalua cada elemento mediante la condicion x<=2 para luego arrojar valores booleanos en cada evaluacion.
* x[x <= 2] Nos arroja los elementos de x cuya posicion coincide con la posicion de todos los TRUE obtenidos en el resultado x<=2.
* x[(x != 5) & (x > 3)] Nos arroja los elementos de x cuya posicion coincide con la posicion de todos los TRUE obtenidos en el resultado (x != 5) & (x > 3).


### e)

* rep(1:4,2) imprimira los valores 1,2,3,4 y los volvera a imprimir.
* rep(1:4,each = 2) repitira cada valor por separado antes de seguir con el siguiente.
* rep(1:4,c(2, 1, 2, 1)) el i-esimo valor de 1:4 lo repetira c[i] veces.
* rep(1:4,each = 2, len = 10) no puedo aun predecir este resultado

In [25]:
rep(1:4,2)
rep(1:4,each = 2)
rep(1:4,c(2, 1, 2, 1))
rep(1:4,each = 2, len = 10)

[1] 1 2 3 4 1 2 3 4

[1] 1 1 2 2 3 3 4 4

[1] 1 1 2 3 3 4

[1] 1 1 2 2 3 3 4 4 1 1

#### obs:
rep(1:4,each = 2, len = 10) repite cada valor dos veces y al poner len=10 indicamos que se devuelvan 10 valores,los que faltan se rellenan repitiendo la secuencia.

### f)

* 2:3^2 mostrara todos los valores desde el 2 hasta el 3^2 es decir 2:9
* seq(2, -3) * c(-1, 1);primero con seq(2,-3) se tendran todos los valores enteros desde el 2 hasta el -3 luego al multiplicarse por c(-1,1) se tendra {-2,1,0,-1,2,-3}

In [9]:
2:3^2
seq(2, -3) * c(-1,1)

[1] 2 3 4 5 6 7 8 9

[1] -2  1  0 -1  2 -3

### 4. Calcula lo siguiente: 

![Sin titulo](matriz4.png)

In [17]:
A <- matrix(c(1,2,7,2,4,6),nrow = 3, ncol= 3)
B <- matrix(c(10,30,50,20,40,60),nrow = 3, ncol= 3)
(2/7)*A-B

[,1]       [,2]      [,3]      
[1,]  -9.714286 -19.42857  -9.714286
[2,] -29.428571 -38.85714 -29.428571
[3,] -48.000000 -58.28571 -48.000000

### 5. Almacena y calcula:

![Sin titulo](matriz5.png)

In [43]:
A <- matrix(c(1,2,7),nrow = 3, ncol= 1)
B <- matrix(c(3,4,8),nrow = 3, ncol= 1)
#A %*% B NO puede resolverse
t(A) %*% B
t(B) %*% (A %*% t(A))
det((B %*% t(B))+(A %*% t(A))-100*diag(1,3)) # diferente de 0,existe inversa!
solve((B %*% t(B))+(A %*% t(A))-100*diag(1,3)) # hallando la inversa

[,1]
[1,] 67

[,1] [,2] [,3]
[1,] 67   134  469

[1] 398300

[,1]         [,2]         [,3]       
[1,] -0.007923676  0.003123274 0.007843334
[2,]  0.003123274 -0.005350239 0.011483806
[3,]  0.007843334  0.011483806 0.017584735

### 6.
##### La función diag tiene varios usos, uno de los cuales es tomar un vector como entrada y crea una matriz cuadrada con ese vector en la diagonal. Crea una matriz 21 × 21 con la secuencia de 10 a 0 y a 10 (es decir, 10, . . . , 1, 0, 1, . . . , 10).

In [44]:
diag(c(seq(10,0),seq(1,10)),21)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ⋯     0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ⋯     0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ⋯     0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ⋯     0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ⋯     0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ⋯     0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ⋯     0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ⋯     1     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[15,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 0     0     0     0     0     0     0      0   
[14,] 3     0     0     0     0     0     0      0   
[15,] 0     4     0     0     0     0     0      0   
[16,] 0     0     5     0     0     0     0      0   
[17,] 0     0     0     6     0     0     0      0   
[18,] 0     0     0     0     7     0     0      0   
[19,] 0     0     0     0     0     8     0      0   
[20,] 0     0     0     0     0     0     9      0   
[21,] 0     0     0     0     0     0     0     10

### 7.

![Sin titulo](matriz7.png)

In [4]:
A <- diag(c(2,3,5,-1),4)
(solve(A)%*%A) - diag(1,4)

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

!!!COMPROBADO!!!

### 8.Usa las funciones matrix() , seq() y rep() para construir la matrices de Henkel 5 × 5.

![Sin titulo](matriz8.png)

In [82]:
M <- matrix(seq(1,5)+rep(0:4,each=5),nrow=5,ncol=5)
M


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

### Convierte el código en una función que puede ser usado para construir matrices de dimensión n × n. Usa esa función para mostrar las salida de Matrices de Henkel de orden 10 × 10 y 12 × 12.

In [84]:


HENKEL <- function(x)
{
  matrix(seq(1,x)+rep(0:(x-1),each=x),nrow=x,ncol=x)
}
# Dimension 10 x10
HENKEL(10)
# Dimension 12 x 12
HENKEL(12)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9   10   
 [2,]  2    3    4    5    6    7    8    9   10   11   
 [3,]  3    4    5    6    7    8    9   10   11   12   
 [4,]  4    5    6    7    8    9   10   11   12   13   
 [5,]  5    6    7    8    9   10   11   12   13   14   
 [6,]  6    7    8    9   10   11   12   13   14   15   
 [7,]  7    8    9   10   11   12   13   14   15   16   
 [8,]  8    9   10   11   12   13   14   15   16   17   
 [9,]  9   10   11   12   13   14   15   16   17   18   
[10,] 10   11   12   13   14   15   16   17   18   19

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,]  1    2    3    4    5    6    7    8    9   10    11    12   
 [2,]  2    3    4    5    6    7    8    9   10   11    12    13   
 [3,]  3    4    5    6    7    8    9   10   11   12    13    14   
 [4,]  4    5    6    7    8    9   10   11   12   13    14    15   
 [5,]  5    6    7    8    9   10   11   12   13   14    15    16   
 [6,]  6    7    8    9   10   11   12   13   14   15    16    17   
 [7,]  7    8    9   10   11   12   13   14   15   16    17    18   
 [8,]  8    9   10   11   12   13   14   15   16   17    18    19   
 [9,]  9   10   11   12   13   14   15   16   17   18    19    20   
[10,] 10   11   12   13   14   15   16   17   18   19    20    21   
[11,] 11   12   13   14   15   16   17   18   19   20    21    22   
[12,] 12   13   14   15   16   17   18   19   20   21    22    23

### 9. La matriz de Hilbert n × n tiene a los elementos ( i, j ) dados por 1/ ( i + j − 1 ) .

* Escribe una función que muestra una matriz de Hilbert n × n como salida para entero positivo n.

In [18]:
Hilbert <- function(n)
{
 M <- matrix(0,nrow = n,ncol= n)
 for(i in 1:n){
     for(j in 1:n){
       M[i,j]<-1/(i+j-1)
     }
  }
 M
}

# Example
Hilbert(9)

[,1]      [,2]      [,3]       [,4]       [,5]       [,6]      
 [1,] 1.0000000 0.5000000 0.33333333 0.25000000 0.20000000 0.16666667
 [2,] 0.5000000 0.3333333 0.25000000 0.20000000 0.16666667 0.14285714
 [3,] 0.3333333 0.2500000 0.20000000 0.16666667 0.14285714 0.12500000
 [4,] 0.2500000 0.2000000 0.16666667 0.14285714 0.12500000 0.11111111
 [5,] 0.2000000 0.1666667 0.14285714 0.12500000 0.11111111 0.10000000
 [6,] 0.1666667 0.1428571 0.12500000 0.11111111 0.10000000 0.09090909
 [7,] 0.1428571 0.1250000 0.11111111 0.10000000 0.09090909 0.08333333
 [8,] 0.1250000 0.1111111 0.10000000 0.09090909 0.08333333 0.07692308
 [9,] 0.1111111 0.1000000 0.09090909 0.08333333 0.07692308 0.07142857
      [,7]       [,8]       [,9]      
 [1,] 0.14285714 0.12500000 0.11111111
 [2,] 0.12500000 0.11111111 0.10000000
 [3,] 0.11111111 0.10000000 0.09090909
 [4,] 0.10000000 0.09090909 0.08333333
 [5,] 0.09090909 0.08333333 0.07692308
 [6,] 0.08333333 0.07692308 0.07142857
 [7,] 0.07692308 0.07142857 0.06666667
 [8,] 0.07142857 0.06666667 0.06250000
 [9,] 0.06666667 0.06250000 0.05882353

* ¿ Son todas las matrices de Hilbert invertibles?.

* Usa solve() y qr.solve() para calcular la inversa de las matrices Hilbert, por ejemplo, cuando n = 10.

In [19]:
solve(Hilbert(10))

[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999719e+01 -4.949757e+03  7.919482e+04 -6.005529e+05       2522295
 [2,] -4.949756e+03  3.266790e+05 -5.880152e+06  4.756344e+07    -208088462
 [3,]  7.919480e+04 -5.880151e+06  1.128980e+08 -9.512635e+08    4280662450
 [4,] -6.005527e+05  4.756343e+07 -9.512634e+08  8.244246e+09  -37871868827
 [5,]  2.522294e+06 -2.080884e+08  4.280662e+09 -3.787187e+10  176734991839
 [6,] -6.305679e+06  5.350810e+08 -1.123668e+10  1.009913e+11 -477183582308
 [7,]  9.608580e+06 -8.323436e+08  1.775667e+10 -1.615857e+11  771204559101
 [8,] -8.750614e+06  7.700557e+08 -1.663323e+10  1.528915e+11 -735791094422
 [9,]  4.375282e+06 -3.898391e+08  8.505604e+09 -7.883452e+10  382044919568
[10,] -9.236661e+05  8.313037e+07 -1.828875e+09  1.706955e+10  -83214282335
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305682e+06  9.608586e+06 -8.750620e+06  4.375286e+06 -9.236669e+05
 [2,]  5.350812e+08 -8.323439e+08  7.700561e+08 -3.898393e+08  8.313042e+07
 [3,] -1.123669e+10  1.775667e+10 -1.663324e+10  8.505608e+09 -1.828876e+09
 [4,]  1.009913e+11 -1.615857e+11  1.528915e+11 -7.883455e+10  1.706956e+10
 [5,] -4.771836e+11  7.712047e+11 -7.357912e+11  3.820450e+11 -8.321430e+10
 [6,]  1.301409e+12 -2.120813e+12  2.037577e+12 -1.064270e+12  2.330005e+11
 [7,] -2.120813e+12  3.480308e+12 -3.363622e+12  1.765901e+12 -3.883348e+11
 [8,]  2.037577e+12 -3.363622e+12  3.267520e+12 -1.723107e+12  3.804102e+11
 [9,] -1.064270e+12  1.765901e+12 -1.723107e+12  9.122340e+11 -2.020931e+11
[10,]  2.330005e+11 -3.883348e+11  3.804101e+11 -2.020931e+11  4.490964e+10

In [65]:
A <- Hilbert(10)

b <- diag(1,10)

qr.solve(A, b,tol=0) # or solve(qr(A), b)

[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999763e+01 -4.949796e+03  7.919566e+04 -6.005606e+05       2522332
 [2,] -4.949794e+03  3.266822e+05 -5.880222e+06  4.756409e+07    -208091541
 [3,]  7.919557e+04 -5.880218e+06  1.128994e+08 -9.512768e+08    4280726081
 [4,] -6.005595e+05  4.756403e+07 -9.512762e+08  8.244364e+09  -37872432943
 [5,]  2.522326e+06 -2.080912e+08  4.280722e+09 -3.787241e+10  176737626224
 [6,] -6.305764e+06  5.350885e+08 -1.123685e+10  1.009928e+11 -477190694526
 [7,]  9.608718e+06 -8.323557e+08  1.775693e+10 -1.615881e+11  771216047252
 [8,] -8.750745e+06  7.700672e+08 -1.663348e+10  1.528938e+11 -735802046037
 [9,]  4.375350e+06 -3.898451e+08  8.505733e+09 -7.883571e+10  382050600435
[10,] -9.236809e+05  8.313167e+07 -1.828903e+09  1.706981e+10  -83215518397
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305784e+06  9.608755e+06 -8.750784e+06  4.375372e+06 -9.236858e+05
 [2,]  5.350897e+08 -8.323580e+08  7.700697e+08 -3.898465e+08  8.313200e+07
 [3,] -1.123686e+10  1.775696e+10 -1.663352e+10  8.505756e+09 -1.828909e+09
 [4,]  1.009929e+11 -1.615883e+11  1.528940e+11 -7.883586e+10  1.706985e+10
 [5,] -4.771909e+11  7.712167e+11 -7.358029e+11  3.820511e+11 -8.321566e+10
 [6,]  1.301428e+12 -2.120845e+12  2.037609e+12 -1.064286e+12  2.330042e+11
 [7,] -2.120844e+12  3.480361e+12 -3.363673e+12  1.765928e+12 -3.883407e+11
 [8,]  2.037607e+12 -3.363671e+12  3.267568e+12 -1.723133e+12  3.804158e+11
 [9,] -1.064285e+12  1.765927e+12 -1.723132e+12  9.122472e+11 -2.020961e+11
[10,]  2.330039e+11 -3.883404e+11  3.804156e+11 -2.020960e+11  4.491027e+10